osx_image: xcode11.4.1
language: objective-c
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod repo update
- pod install
script: xcodebuild -workspace RadioRasclat.xcworkspace -scheme RadioRasclat -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO