# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

copyright "#{Time.now.year} Radio Rasclat e.V."