# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Run tests"
  lane :test do
    scan(scheme: "RadioRasclat")
  end

  desc "Take screenshots"
  lane :screenshots do
    snapshot
  end

  desc "Build application"
  lane :build do
    build_number = number_of_commits
    increment_build_number(
      xcodeproj: "RadioRasclat.xcodeproj",
      build_number: build_number
    )
    build_ios_app(
      scheme: "RadioRasclat"
    )
  end

  desc "Upload metadata, screenshots and binary"
  lane :upload do
    deliver(
      force: true,
      automatic_release: false,
      submit_for_review: false
    )
  end

  desc "Push a new beta build to Testflight"
  lane :beta do
    ensure_git_status_clean
    test
    cert
    sigh(force: true)
    build
    upload_to_testflight
  end
end
