name: Beta Distribution

on:
  push:
    branches: [ beta ]

jobs:
  distribute:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: setup fastlane
        run: bundle install
      - name: distribute to testflight
        env:
          APPLE_ACCOUNT: ${{ secrets.APPLE_ACCOUNT }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
        run: bundle exec fastlane beta