name: Beta Distribution

on:
  push:
    branches: [ beta ]

jobs:
  distribute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: setup fastlane
        run: bundle install
      - name: distribute to firebase
        run: bundle exec fastlane beta