name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: xcodebuild -scheme RadioRasclat -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.2' build test
    - uses: codecov/codecov-action@v1